import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Christopher Kühtz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Christopher Kühtz, Frontend Developer</h1>
        <h2>Frameworks,Languages und Skills</h2>
        <ul>
          <li>
            <h3>Frameworks</h3>
          </li>
          <li>React</li>
          <li>Vue</li>
          <li>Next.js</li>
          <li>
            <h3>Tools</h3>
          </li>
          <li>Typescript</li>
          <li>Redux</li>
          <li>Keycloak</li>
          <li>
            <h3>Design Tools</h3>
          </li>
          <li>Material Ui</li>
          <li>Bootstrap</li>
          <li>SASS</li>
          <li>
            <h3>Testing</h3>
          </li>
          <li>Jest</li>
          <li>CodeceptJS</li>
          <li>
            <h3>Um den Code herum</h3>
          </li>
          <li>
            Erfahrung als Scrum Master (Organisation von Sprints und
            Retrospektiven)
          </li>
          <li>
            hervorragende Englischkenntnisse, mittelmäßig Spanisch, Anfänger
            Französisch
          </li>
        </ul>
        <h2>Meine Erfahrungen als Entwickler</h2>
        <ul>
          <li>
            <h3>Wechselgott</h3>
            <p>06.2021-heute</p>
            <p>
              Aktuell arbeite ich bei dem Startup Unternehmen{" "}
              <a href="wechselgott.de">Wechselgott</a>als Frontend Entwickler.
              In meiner Zeit hier habe ich mit React, Typescript, Material UI
              und Redux neue Features für unsere Web App entwickelt, an dem
              Entwurf und der Implementierung einer neuen Frontend und Design
              Architektur mitgearbeitet und ein End to End Testing System mit
              Codecept JS und integriertem Reporting an Jira erstellt. Außerdem
              habe ich in den letzten Monaten mein Team als Teilzeit Scrum
              Master unterstützt, indem ich unsere Daily Meetings und
              Retrospektiven organisiert habe.
            </p>
          </li>
          <li>
            <h3>Codecamp:N</h3>
            <p>10.2020-04.2021</p>
            <p>
              Ich war bei <a href="codecamp-n.de">CodeCamp:N</a>, einer
              Tochtergesellschaft der Nürnberger Versicherung, für 6 Monate als
              Praktikant in der Frontend Entwicklung tätig. Im Projekt{" "}
              <a href="meine-vorsorgedokumente.de">Meine Vorsorgedokumente</a>{" "}
              habe ich neue Features mit Vue.js entwickelt und maßgeblich das
              Design der Web App mit Bootstrap und einem custom SCSS theme
              umgebaut.
            </p>
          </li>
          <li>
            <h3>Mantro dev.jetzt Bootcamp</h3>
            <p>02.2020-03.2020</p>
            <p>
              Meine erste offizielle Erfahrung als Entwickler war das dev.jetzt
              Bootcamp von Mantro. Als einer von 12 Teilnehmern
              (Bewerbungsprozess, Teilnahme kostenlos) habe ich über 3 Wochen
              einen Einblick in den MERN Stack und in die Prozesse der Software
              Entwicklung bekommen.
            </p>
          </li>
        </ul>
        <h2>Meine Projekte und Kurse</h2>
        <ul>
          <li>
            <h3>Pokemon Micro Frontends</h3>
            <p>Github Link</p>
            <p>
              In diesem Projekt entwickle ich ein klassisches Nintendo Pokemon
              Spiel als Micro Frontend Architektur. Ich habe Teilkomponenten des
              Spiels (z.B. Item Tasche, Overworld View, Battle View) in einzelne
              React Apps gegliedert, die von einer Haupt App importiert werden
              können. Diese Architekur erlaubt es mir, einzelne Teile des
              Projekts separat zu deployen, oder sie in verschiedenen "Haupt
              Apps" gleichzeitig zu benutzen
            </p>
          </li>
          <li>
            <h3>Full Stack Open U of Helsinki</h3>
            <p>
              <a href="https://fullstackopen.com/en/">
                https://fullstackopen.com/en/
              </a>
            </p>
            <p>
              Mit diesem kostenlosen Kurs (mit bewerteten Übungen) der
              Universität von Helsinki vertiefe ich im Moment mein Wissen über
              Full Stack Development. Besonders möchte ich mehr strukturierte
              Frontend Backend Kommunikation und GraphQL Datenbanken lernen.
            </p>
          </li>
        </ul>
        <h2>Wie und warum ich zum Entwickler wurde</h2>
        <ul>
          <li>
            <h3>Bevor ich Entwickler war ...</h3>

            <p>
              .. habe ich für zu lange Zeit an der Friedrich Alexander
              Universität Erlangen Nürnberg meinen Abschluss als B.Sc.
              International Production Engineering verfolgt. Im Zuge meiner
              Bachelorarbeit hatte ich erste Kontakte mit der Programmierung,
              indem ich ein Skript geschrieben habe, um exportierte Koordinaten
              aus einem CAD Programm in einem anderen nutzbar zu machen. Leider
              musste ich 2019 mein Studium, trotz abgeschlossener
              Bachelorarbeit, wegen einer nicht bestandenen Prüfung ohne
              Abschluss beenden.
            </p>
          </li>
          <li>
            <h3>Wie</h3>
            <p>Github Link</p>
            <p>
              In diesem Projekt entwickle ich ein klassisches Nintendo Pokemon
              Spiel als Micro Frontend Architektur. Ich habe Teilkomponenten des
              Spiels (z.B. Item Tasche, Overworld View, Battle View) in einzelne
              React Apps gegliedert, die von einer Haupt App importiert werden
              können. Diese Architekur erlaubt es mir, einzelne Teile des
              Projekts separat zu deployen, oder sie in verschiedenen "Haupt
              Apps" gleichzeitig zu benutzen
            </p>
          </li>
          <li>
            <h3>Warum</h3>
            <p>
              <a href="https://fullstackopen.com/en/">
                https://fullstackopen.com/en/
              </a>
            </p>
            <p>
              Mit diesem kostenlosen Kurs (mit bewerteten Übungen) der
              Universität von Helsinki vertiefe ich im Moment mein Wissen über
              Full Stack Development. Besonders möchte ich mehr strukturierte
              Frontend Backend Kommunikation und GraphQL Datenbanken lernen.
            </p>
          </li>
        </ul>
      </main>
    </div>
  );
}
