import {
  Stack,
  Container,
  useMediaQuery,
  FormGroup,
  Switch,
  FormControlLabel,
  Box,
} from "@mui/material";
import Head from "next/head";
import Header from "../segments/Header";
import WorkExperience from "../segments/WorkExperience";
import Projects from "../segments/Projects";
import Courses from "../segments/Courses";
import History from "../segments/History";
import ContactMe from "../segments/ContactMe";
import SwipableTemplate from "../templates/SwipableTemplate";
import { useTheme } from "@mui/system";
import { de, eng } from "../data/cv";
import { useState } from "react";

export default function Home() {
  const theme = useTheme();
  const SmOrUp = useMediaQuery(theme.breakpoints.up("sm"));
  const [english, setEnglish] = useState(true);
  return (
    <div>
      <Head>
        <title>Christopher K{english ? "u" : "ü"}htz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container sx={{ py: 3 }} maxWidth="md">
          <Box sx={{ display: "flex", justifyContent: "flex-end" }}>
            <FormGroup>
              <FormControlLabel
                control={<Switch defaultChecked />}
                label={english ? "english" : "deutsch"}
                onClick={() => setEnglish(!english)}
              />
            </FormGroup>
          </Box>

          <Stack spacing={3} direction="column">
            <Header
              header={english ? eng.header : de.header}
              english={english}
            />
            <WorkExperience
              workHistory={english ? eng.workHistory : de.workHistory}
            />
            <Projects projects={english ? eng.openSource : de.openSource} />
            <Projects projects={english ? eng.projects : de.projects} />
            <Courses courses={english ? eng.courses : de.courses} />
            {/* <History history={english ? eng.history : de.history} /> */}
          </Stack>
        </Container>

        {/* <Container>
            <SwipableTemplate>
              <Header
                header={english ? eng.header : de.header}
                english={english}
              />
              <WorkExperience
                workHistory={english ? eng.workHistory : de.workHistory}
              />
              <Projects projects={english ? eng.projects : de.projects} />
              <Courses courses={english ? eng.courses : de.courses} />
              <History history={english ? eng.history : de.history} />
            </SwipableTemplate>
          </Container> */}
      </main>
    </div>
  );
}
